# Generated by Django 6.0.2 on 2026-06-16 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0016_doctor_receptionist_helper_login_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='HelperID',
            field=models.ForeignKey(blank=True, db_column='HelperID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_patients', to='HclsWebApi.helper'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ReceptionistID',
            field=models.ForeignKey(blank=True, db_column='ReceptionistID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_patients', to='HclsWebApi.receptionist'),
        ),
    ]
